name: Lint PRs

on:
  pull_request:
    branches:
      - master

jobs:
  
  cancel_previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  lint_pr:
    name: Lint PR on upload
    runs-on: ubuntu-latest
    needs: cancel_previous

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Whole repo history

      - name: Set-up and configure Ruby
        uses: ruby/setup-ruby@v1.148.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.THORBOT_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger
